sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
node_js:
  - '8.7.0'
before_script:
  - npm prune
script:
  - npm run cover
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
