sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
node_js:
  - '8.7.0'
before_script:
  - npm prune
script:
  - npm run cover
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
